# This is a basic workflow to help you get started with Actions

name: Update notion page

# Controls when the action will run.
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-notion-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Update Notion Task
        run: yarn && node ./index.js
        env:
          NOTION_BOT_SECRET_KEY: ${{ secrets.NOTION_BOT_SECRET_KEY }}
